### ISSUE TITLE
Usage Error: The nearest package directory

### ISSUE THREAD

**Issue by ilyar** [kokkekpek/vendee#1]
```shell
$ node -v && npm -v && yarn -v
v18.16.0
9.6.5
3.6.0
$ mkdir myo && cd $_
$ npx vendee@latest
Need to install the following packages:
  vendee@1.1.5
Ok to proceed? (y) y
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
██╗   ██╗███████╗███╗   ██╗██████╗ ███████╗███████╗
██║   ██║██╔════╝████╗  ██║██╔══██╗██╔════╝██╔════╝
██║   ██║█████╗  ██╔██╗ ██║██║  ██║█████╗  █████╗  
╚██╗ ██╔╝██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██╔══╝  
 ╚████╔╝ ███████╗██║ ╚████║██████╔╝███████╗███████╗
  ╚═══╝  ╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚══════╝

✔ Init project · yes
Usage Error: The nearest package directory (/home/ilyar/hack/myo) doesn't seem to be part of the project declared in /home/ilyar.

- If /home/ilyar isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /home/ilyar is intended to be a project, it might be that you forgot to list hack/myo in its workspace configuration.
- Finally, if /home/ilyar is fine and you intend hack/myo to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
Error: Command failed: yarn install
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at installPackages (/home/ilyar/.npm/_npx/4eb6948dcc0ccdb0/node_modules/vendee/build/cli/actions/init/init.js:26:38)
    at init (/home/ilyar/.npm/_npx/4eb6948dcc0ccdb0/node_modules/vendee/build/cli/actions/init/init.js:15:5)
    at showInitMenu (/home/ilyar/.npm/_npx/4eb6948dcc0ccdb0/node_modules/vendee/build/cli/menus/showInitMenu.js:17:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/home/ilyar/.npm/_npx/4eb6948dcc0ccdb0/node_modules/vendee/build/cli/init.js:35:9)
    at async main (/home/ilyar/.npm/_npx/4eb6948dcc0ccdb0/node_modules/vendee/build/cli/index.js:19:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 577376,
  stdout: null,
  stderr: null
}

```

**Comment by ilyar** [comment]
```shell
rm ~/package.json
```
